### ISSUE TITLE
設定GitHub Page

### ISSUE THREAD

**Issue by pulipulichen** [billxu0521/GA-project#1]
![2017-02-03_093812](https://cloud.githubusercontent.com/assets/2345913/22576136/dd42f64a-e9f4-11e6-9d18-7bad49cc6706.png)

http://blog.kejyun.com/2013/06/Build-Web-Page-On-Github.html
在settings裡面
用master branch設定

**Comment by billxu0521** [comment]
設定完成
位置：https://billxu0521.github.io/GA-project/
