### ISSUE TITLE
計時器功能錯誤，請見#TODO ga_inject_lib.js

### ISSUE THREAD

**Issue by pulipulichen** [billxu0521/GA-project#2]
https://github.com/billxu0521/GA-project/blob/master/ga_inject_lib.js
寫得不好
同時呼叫多個需要計時的功能時，就會出錯
請修正

**Comment by pulipulichen** [comment]
如果不知道怎麼寫的話，提示是「為timer加上可動態設定的名稱」

例如 var _timer_array["timer_scroll_" + _event_type] = setTimeout(...);
以及clearTimeout("timer_scroll_" + _event_type);

用這個方式來重寫吧

**Comment by billxu0521** [comment]
20170205 修改成動態設定名稱的計時器
